sudo: false
language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "stable"

before_script:
  - npm install coffeescript -g

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
